apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-api-config
data:
  connection_string: Username=postgres;Password=postgres;Include Error Detail=True;Host=postgres-svc:5432;Port=5432;Database=inventory

