apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-api-config
data:
  postgres_host: postgres-svc:5432
  connection_string: "Host=postgres-svc:5432;User ID=postgres;Password=postgres;Database=inventory"
  appsettings.Development.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "origins": "*"
    }
    
      
      