apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-api
  labels:
    app: inventory-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-api
  
  template:
    metadata:
      name: inventory-api
      labels:
        app: inventory-api
    spec:
      restartPolicy: Always
      
      containers:
        - name: inventory-api
          image: inventory-api
          imagePullPolicy: Never      
          ports:
            - containerPort: 80
              name: api
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__DBConnection
              valueFrom:
                configMapKeyRef:
                  key: connection_string
                  name: inventory-api-config
          volumeMounts:
            - mountPath: /app/appsettings.Development.json
              subPath: appsettings.Development.json
              name: inventory-config
                  
      volumes:
        - name: inventory-config
          configMap:
            name: inventory-api-config
    

  
