apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-api
  labels:
    app: inventory-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-api
  
  template:
    metadata:
      name: inventory-api
      labels:
        app: inventory-api
    spec:
      restartPolicy: Always
      
      containers:
        - name: inventory-api
          image: inventory-api
          imagePullPolicy: Never          
          env:
            - name: ConnectionStrings__DBConnection
              valueFrom:
                configMapKeyRef:
                - name: inventory-api-config 
                  key: connection_string
                  
    

  
